# config/routes.yaml

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: annotation

front:
  resource: 'routes/front.yaml'
  prefix: /{_locale}/
  requirements:
    _locale: '%app_locales%'

app_logout:
  path: /logout
  methods: GET

homepage:
  path: /{_locale}
  requirements:
    _locale: '%app_locales%'
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: /homepage/index.html.twig
    _locale: '%locale%'

newpost:
  path: /newpost
  controller: App\Controller\PostController::new
